language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
script: echo "-------- Running 0.19.9 tests --------"" && mvn test -P 0.19.9 && echo "-------- Running 0.19.10 tests --------" && mvn test -P 0.19.10
